/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Value = string;
export type Label = string;
export type AdvancedSearchJson = {
  value?: Value;
  label?: Label;
  [k: string]: unknown;
}[];
