/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string;
export type HeroBanner = string;
export type SearchURL = string;
export type BrowseByCategoryTitle = string;
export type CalendarfilterOption = string;
export type DatabaseName = string;
export type DisplayTitle = string;
export type LinkURL = string;
export type Thumbnail = string;
export type Title = string;
export type Url = string;
export type CategoriesItems = {
  thumbnail?: Thumbnail;
  title?: Title;
  url?: Url;
  [k: string]: unknown;
}[];
export type Title1 = string;
export type Description = string;
export type Url1 = string;
export type Thumbnail1 = string;
export type FeaturedCollection = {
  title?: Title1;
  description?: Description;
  url?: Url1;
  thumbnail?: Thumbnail1;
  [k: string]: unknown;
}[];
export type FilterDatabase = string;
export type FilterOption = string;
export type FilterTypes = unknown[];
export type EnableCategoriesItems = boolean;
export type EnableFeaturedCollection = boolean;
export type EnableRSVP = boolean;
export type EnableRecentAddition = boolean;

export interface ArchivesJson {
  heading?: Heading;
  heroBanner?: HeroBanner;
  searchURL?: SearchURL;
  browseByCategoryTitle?: BrowseByCategoryTitle;
  CalendarfilterOption?: CalendarfilterOption;
  database_name?: DatabaseName;
  displayTitle?: DisplayTitle;
  linkURL?: LinkURL;
  categoriesItems?: CategoriesItems;
  featuredCollection?: FeaturedCollection;
  rsvp?: Rsvp;
  enableCategoriesItems?: EnableCategoriesItems;
  enableFeaturedCollection?: EnableFeaturedCollection;
  enableRSVP?: EnableRSVP;
  enableRecentAddition?: EnableRecentAddition;
  [k: string]: unknown;
}
export interface Rsvp {
  filterDatabase?: FilterDatabase;
  filterOption?: FilterOption;
  filterTypes?: FilterTypes;
  [k: string]: unknown;
}
