/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number
export type Label = string
export type Db = string
export type Icon = string
export type Url = string
export type Database = {
	id?: Id
	label?: Label
	db?: Db
	icon?: Icon
	url?: Url
	[k: string]: unknown
}[]

export interface ClientProfileJson {
	database?: Database
	[k: string]: unknown
}
