/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SiteName = string
export type Logo = string
export type Login = boolean
export type Url = string
export type ReCaptchaKey = string
export type Url1 = string
export type Title = string
export type SearchDatabase = string
export type Navigations = {
	url?: Url1
	title?: Title
	search_database?: SearchDatabase
	[k: string]: unknown
}[]

export interface ConfigJson {
	siteName?: SiteName
	logo?: Logo
	auth?: Auth
	reCaptchaKey?: ReCaptchaKey
	navigations?: Navigations
	[k: string]: unknown
}
export interface Auth {
	login?: Login
	url?: Url
	[k: string]: unknown
}
