/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SiteName = string
export type Logo = string
export type Url = string
export type Title = string
export type Navigations = {
	url?: Url
	title?: Title
	[k: string]: unknown
}[]

export interface ConfigJson {
	siteName?: SiteName
	logo?: Logo
	navigations?: Navigations
	[k: string]: unknown
}
