/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string;
export type SubHeading = string;
export type HeroBanner = string;

export interface FaqJson {
  heading?: Heading;
  subHeading?: SubHeading;
  heroBanner?: HeroBanner;
  [k: string]: unknown;
}
