/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string;
export type HeroBanner = string;
export type SearchURL = string;
export type BrowseByCategoryTitle = string;
export type CalendarfilterOption = string;
export type DatabaseName = string;
export type Thumbnail = string;
export type Title = string;
export type Url = string;
export type CategoriesItems = {
  thumbnail?: Thumbnail;
  title?: Title;
  url?: Url;
  [k: string]: unknown;
}[];
export type FilterDatabase = string;
export type FilterOption = string;
export type Type = string;
export type Color = string;
export type Icon = string;
export type FilterTypes = {
  type?: Type;
  color?: Color;
  icon?: Icon;
  [k: string]: unknown;
}[];

export interface LibraryJson {
  heading?: Heading;
  heroBanner?: HeroBanner;
  searchURL?: SearchURL;
  browseByCategoryTitle?: BrowseByCategoryTitle;
  CalendarfilterOption?: CalendarfilterOption;
  database_name?: DatabaseName;
  categoriesItems?: CategoriesItems;
  rsvp?: Rsvp;
  [k: string]: unknown;
}
export interface Rsvp {
  filterDatabase?: FilterDatabase;
  filterOption?: FilterOption;
  filterTypes?: FilterTypes;
  [k: string]: unknown;
}
